version: "3"
services:
  api:
    image: lexic
    build: .
    networks:
      - backend
    ports:
      - "8000:8000"

  web-cli:
    image: lexic
    networks:
      - backend
    command: sh

networks:
  backend:
    driver: bridge
